const btnEl = document.querySelector(".btn"); //define generate button
const inputEl = document.getElementById("input"); //define input area
const copyIconEl = document.querySelector(".fa-copy"); //define copy button
const alertContainerEl = document.querySelector(".alert-container"); //define alert text

//when click the generate button, call the createpassword function
btnEl.addEventListener("click", () => {
  createPassword();
});

//if there is a value in the input area, the alert text can show. But there is no password in the input area,then the alert text can not show.
copyIconEl.addEventListener("click", () => {
  copyPassword();
  if (inputEl.value) {
    alertContainerEl.classList.remove("active");
    setTimeout(() => {
      alertContainerEl.classList.add("active");
    }, 2000); //show time of the alert text
  }
});

//in this function, select random characters from 'chars' string. the password is generated by 14 characters.
function createPassword() {
  const chars =
    "0123456789abcdefghijklmnopqrstuvwxtz!@#$%^&*()_+?:{}[]ABCDEFGHIJKLMNOPQRSTUVWXYZ";
  const passwordLength = 14;
  let password = "";
  for (let index = 0; index < passwordLength; index++) {
    const randomNum = Math.floor(Math.random() * chars.length);
    password += chars.substring(randomNum, randomNum + 1);
  }
  inputEl.value = password;
  alertContainerEl.innerText = "Password Copied!";
}

function copyPassword() {
  inputEl.select();
  inputEl.setSelectionRange(0, 9999);
  navigator.clipboard.writeText(inputEl.value);
}